name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated universal APK file
      uses: actions/upload-artifact@v2
      with:
        name: Instabar-app-universal
        path: |
            ./app/build/outputs/apk/**/Instabar_universal.apk
            ./app/build/outputs/apk/github/debug/output-metadata.json
